{% set name = "pydeck-carto" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ceec71f9e9667d65cc8647ad1bca57bb48ab4fbb9627a732c3e44735c982858

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydeck >=0.8.0
    - carto-auth >=0.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydeck_carto

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck-carto
  summary: Pydeck wrapper for use with CARTO
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pydeck-carto.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/blob/master/bindings/pydeck-carto

extra:
  recipe-maintainers:
    - Jesus89
